export const dynamic = "force-dynamic";

import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { BellRing, AlertTriangle, CheckCircle2 } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { getBusinessByUserId } from "@/lib/db";
import { getNotificationsByUserId } from "@/lib/ops-side-effects";

function getPriorityClasses(priority: string) {
  if (priority === "urgent") return "bg-red-100 text-red-700";
  if (priority === "high") return "bg-orange-100 text-orange-700";
  if (priority === "medium") return "bg-yellow-100 text-yellow-700";
  return "bg-gray-100 text-gray-700";
}

function getStatusClasses(status: string) {
  if (status === "unread") return "bg-brand-50 text-brand-700";
  return "bg-gray-100 text-gray-600";
}

export default async function NotificationsPage() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) redirect("/login");

  const business = await getBusinessByUserId(session.user.id);
  if (!business) redirect("/onboarding");

  const notifications = await getNotificationsByUserId(session.user.id, 100);
  const unreadCount = notifications.filter((notification) => notification.status === "unread").length;
  const urgentCount = notifications.filter((notification) => notification.priority === "urgent" || notification.priority === "high").length;

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Notification Center</h1>
          <p className="mt-1 max-w-2xl text-sm text-gray-500">
            Priority alerts generated by Frontline operations events, urgent leads, schedule requests, and order issues.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <div className="rounded-xl border border-gray-200 bg-white p-3">
          <div className="flex items-center gap-2 text-brand-600">
            <BellRing size={16} />
            <p className="text-xs">Total</p>
          </div>
          <p className="mt-1 text-2xl font-bold text-gray-900">{notifications.length}</p>
        </div>
        <div className="rounded-xl border border-gray-200 bg-white p-3">
          <div className="flex items-center gap-2 text-orange-600">
            <AlertTriangle size={16} />
            <p className="text-xs">Priority</p>
          </div>
          <p className="mt-1 text-2xl font-bold text-orange-600">{urgentCount}</p>
        </div>
        <div className="rounded-xl border border-gray-200 bg-white p-3">
          <div className="flex items-center gap-2 text-emerald-600">
            <CheckCircle2 size={16} />
            <p className="text-xs">Unread</p>
          </div>
          <p className="mt-1 text-2xl font-bold text-emerald-600">{unreadCount}</p>
        </div>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white">
        <div className="border-b border-gray-100 px-4 py-3">
          <h2 className="text-base font-semibold text-gray-900">Alerts</h2>
          <p className="mt-1 text-xs text-gray-500">High and urgent operations events create notifications automatically.</p>
        </div>

        {notifications.length === 0 ? (
          <div className="flex min-h-[320px] items-center justify-center p-6 text-center">
            <div>
              <BellRing className="mx-auto h-8 w-8 text-gray-300" />
              <p className="mt-3 text-sm font-medium text-gray-900">No notifications yet</p>
              <p className="mt-1 max-w-sm text-xs text-gray-500">
                High-priority or urgent operational events will appear here automatically.
              </p>
            </div>
          </div>
        ) : (
          <div className="max-h-[560px] divide-y divide-gray-100 overflow-y-auto">
            {notifications.map((notification) => (
              <div key={notification.id} className="p-4 hover:bg-gray-50 transition-colors">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <h3 className="text-sm font-semibold text-gray-900">{notification.title}</h3>
                      <span className={`rounded-full px-2.5 py-0.5 text-[11px] font-medium capitalize ${getPriorityClasses(notification.priority)}`}>
                        {notification.priority}
                      </span>
                      <span className={`rounded-full px-2.5 py-0.5 text-[11px] font-medium capitalize ${getStatusClasses(notification.status)}`}>
                        {notification.status}
                      </span>
                    </div>
                    <p className="mt-1 text-xs text-gray-500 capitalize">
                      {notification.type.replaceAll("_", " ")} · {notification.related_entity_type ?? "operation"}
                    </p>
                    <p className="mt-2 text-sm text-gray-700">{notification.message ?? "No message saved."}</p>
                  </div>
                  <p className="shrink-0 text-xs text-gray-400">
                    {new Date(notification.created_at).toLocaleString()}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
